apiVersion: aws.backstage.io/v1alpha
kind: AWSEnvironmentProvider
metadata:
  name: AWS-Development-Pub-Environment-Provider
  description: An AWS public development environment provider
  env-type: ecs-fargate
  # env-type: ecs-fargate, ecs-ec2, eks
  aws-account: {{ aws-account }}
  aws-region: us-east-1
  vpc: /baws/app-dev-network1
  cluster-name: /baws/baws-public-dev-app-runtime
spec:
  type: environment-provider
  lifecycle: experimental
  owner: group:dev-ops
  system: demo
  dependsOn: ['awsenvironment:AWS-Development-Pub-Environment']
