apiVersion: aws.backstage.io/v1alpha
kind: AWSEnvironmentProvider
metadata:
  name: AWS-Production-Pr-Environment-Provider
  description: An AWS private production environment provider
  env-type: ecs-fargate
  # env-type: ecs-fargate, ecs-ec2, eks
  aws-account: {{ aws-account }}
  aws-region: us-east-1
  vpc: /baws/app-prod-network2
  cluster-name: /baws/baws-isolated-prod-app-runtime
spec:
  type: environment-provider
  lifecycle: experimental
  owner: group:dev-ops
  system: demo
  dependsOn: ['awsenvironment:AWS-Prod-Pr-Environment']
