AppPrefix: "baws"
Account: "123456789012"
Region: "us-east-1"
ReplicaRegion: "us-west-2"
OktaConfigSecret: "baws-okta-secrets"
DbConfigSecret: "baws-db-secrets"
GitlabSecret: "baws-admin-gitlab-secrets"
GitlabAmi: "ami-08bd402cb9916c2e3"
R53HostedZoneName: "backstage.mycompany.com"
AllowedIPs:
  - 1.2.3.4/32
